In [1]:
import json
import os
import dotenv

import numpy as np
import pandas as pd

from sklearn.cluster import HDBSCAN

import sqlalchemy as sa
from sqlalchemy import select, create_engine

from models import Wards, Matches, Players

dotenv.load_dotenv()

True

In [2]:
db = create_engine(os.environ['DB_URL'])

In [3]:
df = pd.DataFrame(pd.read_sql(
    sql=select(Wards, Matches, Players).join(Players, Wards.player_placed).join(Matches).where(sa.and_(Wards.is_obs, Matches.league_id == 15728)).order_by(Matches.id.desc()),
    con=db
))

In [4]:
df['duration'] = df[['duration', 'duration_1', 'time_placed']].apply((lambda row: min(row['duration'], row['duration_1'] - row['time_placed'])), axis=1)

In [5]:
hdbscan = HDBSCAN(
    cluster_selection_epsilon=70,
    min_samples=5,
    min_cluster_size=5,
    cluster_selection_method='eom',
    n_jobs=-1,
)
hdbscan.fit(df[['x_pos', 'y_pos']])

df['cluster_id'] = hdbscan.labels_

In [6]:
df.groupby('cluster_id').size().sort_values(ascending=False)

cluster_id
-1      641
 57     235
 35     211
 4      151
 3      150
       ...
 101      5
 147      5
 64       5
 157      5
 79       5
Length: 177, dtype: int64

In [7]:
df['advantage'] = df[['is_radiant', 'radiant_networth', 'dire_networth']].apply(lambda row: (row['radiant_networth'] - row['dire_networth']) if row['is_radiant'] else (row['dire_networth'] - row['radiant_networth']), axis=1)
df

,id,match_id,is_obs,is_radiant,is_destroyed,is_post_game,player_placed_id,player_destroyed_id,time_placed,duration,...,id_1,league_id,duration_1,region,date,game_version,id_2,name,cluster_id,advantage
0,837950,7406531302,True,True,False,False,16497807,NaN,1181,360,...,7406531302,15728,2525,1,1698621223,53,16497807,tOfu,57,-1973
1,837949,7406531302,True,False,False,False,256156323,NaN,1179,360,...,7406531302,15728,2525,1,1698621223,53,256156323,Mira,19,1881
2,837948,7406531302,True,False,False,False,113331514,NaN,1139,360,...,7406531302,15728,2525,1,1698621223,53,113331514,Miposhka,100,1699
3,837944,7406531302,True,False,False,False,113331514,NaN,1053,360,...,7406531302,15728,2525,1,1698621223,53,113331514,Miposhka,164,1960
4,837942,7406531302,True,False,False,False,113331514,NaN,1031,360,...,7406531302,15728,2525,1,1698621223,53,113331514,Miposhka,35,1960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5366,827144,7378530387,True,True,True,False,10366616,136829091.0,703,338,...,7378530387,15728,1405,1,1697130044,53,10366616,Sneyking,109,3176
5367,827135,7378530387,True,False,False,False,346412363,NaN,457,360,...,7378530387,15728,1405,1,1697130044,53,346412363,Ari,-1,-1985
5368,827134,7378530387,True,False,False,False,136829091,NaN,357,360,...,7378530387,15728,1405,1,1697130044,53,136829091,Whitemon,46,-1548
5369,827133,7378530387,True,True,False,False,10366616,NaN,354,360,...,7378530387,15728,1405,1,1697130044,53,10366616,Sneyking,148,1548
5370,827121,7378530387,True,False,False,False,346412363,NaN,-32,360,...,7378530387,15728,1405,1,1697130044,53,346412363,Ari,82,-100

In [8]:
grouped = df.groupby(['cluster_id', 'is_radiant']).agg({
        'x_pos': lambda x: round(x.mean()),
        'y_pos': lambda x: round(x.mean()),
        'z_pos': lambda x: x.mode().iloc[0], #- 16384,
        'duration': lambda x: round(x.mean()),
        'time_placed': lambda x: round(x.mean()),
        'advantage': lambda x: round(x.mean()),
        'is_destroyed': 'sum'
    })
grouped['amount'] = df.groupby(['cluster_id', 'is_radiant']).size()
# grouped

In [9]:
players = df[df['cluster_id'] == 1][['player_placed_id', 'name']].groupby(['player_placed_id', 'name']).size().to_frame('amount').reset_index().to_dict(orient='records')
players

[{'player_placed_id': 16497807, 'name': 'tOfu', 'amount': 1},
 {'player_placed_id': 34505203, 'name': 'MinD_ContRoL', 'amount': 2},
 {'player_placed_id': 54580962, 'name': 'iNSaNiA', 'amount': 2},
 {'player_placed_id': 77490514, 'name': 'Boxi', 'amount': 2},
 {'player_placed_id': 81475303, 'name': 'Yamsun', 'amount': 2},
 {'player_placed_id': 85696663, 'name': 'n1ght', 'amount': 1},
 {'player_placed_id': 91730177, 'name': 'Seleri', 'amount': 2},
 {'player_placed_id': 94049589, 'name': 'fng', 'amount': 3},
 {'player_placed_id': 97590558, 'name': 'Ace', 'amount': 1},
 {'player_placed_id': 101259972, 'name': 'Oli~', 'amount': 5},
 {'player_placed_id': 111114687, 'name': 'y`', 'amount': 2},
 {'player_placed_id': 113331514, 'name': 'Miposhka', 'amount': 1},
 {'player_placed_id': 117089283, 'name': 'Pandaboo', 'amount': 1},
 {'player_placed_id': 127565532, 'name': 'Fishman', 'amount': 1},
 {'player_placed_id': 134556694, 'name': 'Solo', 'amount': 3},
 {'player_placed_id': 136829091, 'name': 'Whitemon', 'amount': 4},
 {'player_placed_id': 145065875, 'name': 'sayuw', 'amount': 2},
 {'player_placed_id': 150961567, 'name': 'plAnet', 'amount': 1},
 {'player_placed_id': 152168157, 'name': 'OmaR', 'amount': 2},
 {'player_placed_id': 155332459, 'name': 'Matthew', 'amount': 1},
 {'player_placed_id': 161839895, 'name': 'Antares', 'amount': 2},
 {'player_placed_id': 196878136, 'name': 'Kataomi`', 'amount': 1},
 {'player_placed_id': 256156323, 'name': 'Mira', 'amount': 2},
 {'player_placed_id': 346412363, 'name': 'Ari', 'amount': 1},
 {'player_placed_id': 431770905, 'name': 'TORONTOTOKYO', 'amount': 5}]

In [10]:
players_destroyed = df[df['cluster_id'] != -1].groupby(['cluster_id', 'player_destroyed_id']).agg({'duration': lambda x: round(x.mean())})
players_destroyed['amount'] = df.groupby(['cluster_id', 'player_destroyed_id']).size()
players_destroyed

                                duration  amount
cluster_id player_destroyed_id
0          10366616.0                 42       1
           16497807.0                 37       1
           25907144.0                105       2
           77490514.0                106       3
           81475303.0                108       2
...                                  ...     ...
175        54580962.0                 98       1
           87063175.0                126       1
           101695162.0               150       1
           161839895.0                56       1
           317880638.0               193       1

[1294 rows x 2 columns]

In [11]:
for i in range(len(set(hdbscan.labels_)) - 1):
    current = grouped.loc[i]

    d = {
        'cluster_id': i,
        'x_pos': round(current['x_pos'].mean()),
        'y_pos': round(current['y_pos'].mean()),
        'z_pos': round(current['z_pos'].mean()),
        'radiant': {
            'amount': current.loc[True]['amount'],
            'destroyed': current.loc[True]['is_destroyed'],
            'advantage': current.loc[True]['advantage'],
            'duration': current.loc[True]['duration'],
            'time_placed': current.loc[True]['time_placed']
        } if True in current.index else None,
        'dire': {
            'amount': current.loc[False]['amount'],
            'destroyed': current.loc[False]['is_destroyed'],
            'advantage': current.loc[False]['advantage'],
            'duration': current.loc[False]['duration'],
            'time_placed': current.loc[False]['time_placed']
        } if False in current.index else None,
        'all': {
            'amount': current['amount'].sum(),
            'destroyed': current['is_destroyed'].sum(),
            'advantage': None,
            'duration': round(current['duration'].mean()),
            'time_placed': round(current['time_placed'].mean())
        }
    }

    print(json.dumps(d, indent=4, default=int))

{
    "cluster_id": 0,
    "x_pos": 14834,
    "y_pos": 23287,
    "z_pos": 16784,
    "radiant": {
        "amount": 48,
        "destroyed": 30,
        "advantage": 1528,
        "duration": 193,
        "time_placed": 1522
    },
    "dire": {
        "amount": 44,
        "destroyed": 15,
        "advantage": -801,
        "duration": 285,
        "time_placed": 1697
    },
    "all": {
        "amount": 92,
        "destroyed": 45,
        "advantage": null,
        "duration": 239,
        "time_placed": 1610
    }
}
{
    "cluster_id": 1,
    "x_pos": 8453,
    "y_pos": 18196,
    "z_pos": 16920,
    "radiant": {
        "amount": 23,
        "destroyed": 8,
        "advantage": -2683,
        "duration": 270,
        "time_placed": 1991
    },
    "dire": {
        "amount": 27,
        "destroyed": 8,
        "advantage": 77,
        "duration": 289,
        "time_placed": 1661
    },
    "all": {
        "amount": 50,
        "destroyed": 16,
        "advantage": null,
        "duration": 280,
        "time_placed": 1826
    }
}
{
    "cluster_id": 2,
    "x_pos": 24048,
    "y_pos": 13804,
    "z_pos": 16640,
    "radiant": {
        "amount": 2,
        "destroyed": 0,
        "advantage": 5680,
        "duration": 360,
        "time_placed": 1402
    },
    "dire": {
        "amount": 3,
        "destroyed": 0,
        "advantage": -384,
        "duration": 360,
        "time_placed": 1214
    },
    "all": {
        "amount": 5,
        "destroyed": 0,
        "advantage": null,
        "duration": 360,
        "time_placed": 1308
    }
}
{
    "cluster_id": 3,
    "x_pos": 12275,
    "y_pos": 17922,
    "z_pos": 16920,
    "radiant": {
        "amount": 72,
        "destroyed": 22,
        "advantage": -365,
        "duration": 295,
        "time_placed": 873
    },
    "dire": {
        "amount": 78,
        "destroyed": 39,
        "advantage": 1399,
        "duration": 245,
        "time_placed": 1262
    },
    "all": {
        "amount": 150,
        "destroyed": 61,
        "advantage": null,
        "duration": 270,
        "time_placed": 1068
    }
}
{
    "cluster_id": 4,
    "x_pos": 18952,
    "y_pos": 9210,
    "z_pos": 16792,
    "radiant": {
        "amount": 69,
        "destroyed": 29,
        "advantage": -2025,
        "duration": 274,
        "time_placed": 1663
    },
    "dire": {
        "amount": 82,
        "destroyed": 40,
        "advantage": 2690,
        "duration": 247,
        "time_placed": 1468
    },
    "all": {
        "amount": 151,
        "destroyed": 69,
        "advantage": null,
        "duration": 260,
        "time_placed": 1566
    }
}
{
    "cluster_id": 5,
    "x_pos": 15712,
    "y_pos": 24184,
    "z_pos": 16512,
    "radiant": {
        "amount": 15,
        "destroyed": 3,
        "advantage": 2488,
        "duration": 320,
        "time_placed": 1226
    },
    "dire": {
        "amount": 1,
        "destroyed": 0,
        "advantage": 1345,
        "duration": 360,
        "time_placed": 916
    },
    "all": {
        "amount": 16,
        "destroyed": 3,
        "advantage": null,
        "duration": 340,
        "time_placed": 1071
    }
}
{
    "cluster_id": 6,
    "x_pos": 16447,
    "y_pos": 25075,
    "z_pos": 16896,
    "radiant": {
        "amount": 11,
        "destroyed": 1,
        "advantage": -1517,
        "duration": 328,
        "time_placed": 1308
    },
    "dire": {
        "amount": 12,
        "destroyed": 0,
        "advantage": -3946,
        "duration": 358,
        "time_placed": 2291
    },
    "all": {
        "amount": 23,
        "destroyed": 1,
        "advantage": null,
        "duration": 343,
        "time_placed": 1800
    }
}
{
    "cluster_id": 7,
    "x_pos": 17420,
    "y_pos": 19698,
    "z_pos": 16784,
    "radiant": {
        "amount": 55,
        "destroyed": 34,
        "advantage": 171,
        "duration": 249,
        "time_placed": 1749
    },
    "dire": {
        "amount": 42,
        "destroyed": 20,
        "advantage": -814,
        "duration": 249,
        "time_placed": 1991
    },
    "all": {
        "amount": 97,
        "destroyed": 54,
        "advantage": null,
        "duration": 249,
        "time_placed": 1870
    }
}
{
    "cluster_id": 8,
    "x_pos": 24054,
    "y_pos": 14828,
    "z_pos": 16912,
    "radiant": {
        "amount": 38,
        "destroyed": 18,
        "advantage": -79,
        "duration": 267,
        "time_placed": 1601
    },
    "dire": {
        "amount": 30,
        "destroyed": 10,
        "advantage": -2114,
        "duration": 288,
        "time_placed": 1681
    },
    "all": {
        "amount": 68,
        "destroyed": 28,
        "advantage": null,
        "duration": 278,
        "time_placed": 1641
    }
}
{
    "cluster_id": 9,
    "x_pos": 16859,
    "y_pos": 10076,
    "z_pos": 16512,
    "radiant": {
        "amount": 3,
        "destroyed": 1,
        "advantage": -12688,
        "duration": 306,
        "time_placed": 2013
    },
    "dire": {
        "amount": 2,
        "destroyed": 1,
        "advantage": -3752,
        "duration": 227,
        "time_placed": 1279
    },
    "all": {
        "amount": 5,
        "destroyed": 2,
        "advantage": null,
        "duration": 266,
        "time_placed": 1646
    }
}
{
    "cluster_id": 10,
    "x_pos": 24501,
    "y_pos": 17780,
    "z_pos": 16640,
    "radiant": null,
    "dire": {
        "amount": 7,
        "destroyed": 0,
        "advantage": 512,
        "duration": 357,
        "time_placed": 1834
    },
    "all": {
        "amount": 7,
        "destroyed": 0,
        "advantage": null,
        "duration": 357,
        "time_placed": 1834
    }
}
{
    "cluster_id": 11,
    "x_pos": 24282,
    "y_pos": 16742,
    "z_pos": 16640,
    "radiant": {
        "amount": 14,
        "destroyed": 5,
        "advantage": -3269,
        "duration": 265,
        "time_placed": 2054
    },
    "dire": {
        "amount": 5,
        "destroyed": 2,
        "advantage": 2604,
        "duration": 268,
        "time_placed": 1526
    },
    "all": {
        "amount": 19,
        "destroyed": 7,
        "advantage": null,
        "duration": 266,
        "time_placed": 1790
    }
}
{
    "cluster_id": 12,
    "x_pos": 17224,
    "y_pos": 8634,
    "z_pos": 16512,
    "radiant": {
        "amount": 14,
        "destroyed": 3,
        "advantage": -582,
        "duration": 307,
        "time_placed": 1484
    },
    "dire": {
        "amount": 20,
        "destroyed": 3,
        "advantage": 1700,
        "duration": 324,
        "time_placed": 1142
    },
    "all": {
        "amount": 34,
        "destroyed": 6,
        "advantage": null,
        "duration": 316,
        "time_placed": 1313
    }
}
{
    "cluster_id": 13,
    "x_pos": 17144,
    "y_pos": 11777,
    "z_pos": 16920,
    "radiant": {
        "amount": 32,
        "destroyed": 5,
        "advantage": -507,
        "duration": 327,
        "time_placed": 1258
    },
    "dire": {
        "amount": 35,
        "destroyed": 12,
        "advantage": -384,
        "duration": 283,
        "time_placed": 1018
    },
    "all": {
        "amount": 67,
        "destroyed": 17,
        "advantage": null,
        "duration": 305,
        "time_placed": 1138
    }
}
{
    "cluster_id": 14,
    "x_pos": 13081,
    "y_pos": 9237,
    "z_pos": 16640,
    "radiant": {
        "amount": 8,
        "destroyed": 5,
        "advantage": -14095,
        "duration": 180,
        "time_placed": 3195
    },
    "dire": {
        "amount": 16,
        "destroyed": 9,
        "advantage": 2650,
        "duration": 225,
        "time_placed": 2173
    },
    "all": {
        "amount": 24,
        "destroyed": 14,
        "advantage": null,
        "duration": 202,
        "time_placed": 2684
    }
}
{
    "cluster_id": 15,
    "x_pos": 18064,
    "y_pos": 22400,
    "z_pos": 16512,
    "radiant": {
        "amount": 7,
        "destroyed": 6,
        "advantage": -5835,
        "duration": 210,
        "time_placed": 1752
    },
    "dire": {
        "amount": 1,
        "destroyed": 1,
        "advantage": -11072,
        "duration": 32,
        "time_placed": 1669
    },
    "all": {
        "amount": 8,
        "destroyed": 7,
        "advantage": null,
        "duration": 121,
        "time_placed": 1710
    }
}
{
    "cluster_id": 16,
    "x_pos": 22665,
    "y_pos": 17494,
    "z_pos": 16512,
    "radiant": {
        "amount": 8,
        "destroyed": 5,
        "advantage": 68,
        "duration": 230,
        "time_placed": 1971
    },
    "dire": {
        "amount": 1,
        "destroyed": 0,
        "advantage": -2311,
        "duration": 360,
        "time_placed": 2190
    },
    "all": {
        "amount": 9,
        "destroyed": 5,
        "advantage": null,
        "duration": 295,
        "time_placed": 2080
    }
}
{
    "cluster_id": 17,
    "x_pos": 12137,
    "y_pos": 10197,
    "z_pos": 16640,
    "radiant": {
        "amount": 13,
        "destroyed": 9,
        "advantage": -5709,
        "duration": 173,
        "time_placed": 2527
    },
    "dire": {
        "amount": 8,
        "destroyed": 5,
        "advantage": 1541,
        "duration": 252,
        "time_placed": 2232
    },
    "all": {
        "amount": 21,
        "destroyed": 14,
        "advantage": null,
        "duration": 212,
        "time_placed": 2380
    }
}
{
    "cluster_id": 18,
    "x_pos": 14610,
    "y_pos": 7922,
    "z_pos": 16622,
    "radiant": {
        "amount": 3,
        "destroyed": 0,
        "advantage": -6961,
        "duration": 360,
        "time_placed": 2008
    },
    "dire": {
        "amount": 2,
        "destroyed": 0,
        "advantage": 11838,
        "duration": 360,
        "time_placed": 1974
    },
    "all": {
        "amount": 5,
        "destroyed": 0,
        "advantage": null,
        "duration": 360,
        "time_placed": 1991
    }
}
{
    "cluster_id": 19,
    "x_pos": 17236,
    "y_pos": 21750,
    "z_pos": 16512,
    "radiant": {
        "amount": 8,
        "destroyed": 2,
        "advantage": -2687,
        "duration": 283,
        "time_placed": 1750
    },
    "dire": {
        "amount": 3,
        "destroyed": 1,
        "advantage": 2252,
        "duration": 321,
        "time_placed": 1303
    },
    "all": {
        "amount": 11,
        "destroyed": 3,
        "advantage": null,
        "duration": 302,
        "time_placed": 1526
    }
}
{
    "cluster_id": 20,
    "x_pos": 16730,
    "y_pos": 21071,
    "z_pos": 16512,
    "radiant": {
        "amount": 9,
        "destroyed": 2,
        "advantage": 1843,
        "duration": 313,
        "time_placed": 1130
    },
    "dire": null,
    "all": {
        "amount": 9,
        "destroyed": 2,
        "advantage": null,
        "duration": 313,
        "time_placed": 1130
    }
}
{
    "cluster_id": 21,
    "x_pos": 24639,
    "y_pos": 11758,
    "z_pos": 16512,
    "radiant": {
        "amount": 4,
        "destroyed": 0,
        "advantage": -2405,
        "duration": 360,
        "time_placed": 2433
    },
    "dire": {
        "amount": 2,
        "destroyed": 1,
        "advantage": 1313,
        "duration": 182,
        "time_placed": 2324
    },
    "all": {
        "amount": 6,
        "destroyed": 1,
        "advantage": null,
        "duration": 271,
        "time_placed": 2378
    }
}
{
    "cluster_id": 22,
    "x_pos": 14655,
    "y_pos": 9823,
    "z_pos": 16512,
    "radiant": {
        "amount": 3,
        "destroyed": 3,
        "advantage": -1181,
        "duration": 176,
        "time_placed": 2770
    },
    "dire": {
        "amount": 20,
        "destroyed": 11,
        "advantage": 2281,
        "duration": 250,
        "time_placed": 1711
    },
    "all": {
        "amount": 23,
        "destroyed": 14,
        "advantage": null,
        "duration": 213,
        "time_placed": 2240
    }
}
{
    "cluster_id": 23,
    "x_pos": 15454,
    "y_pos": 8614,
    "z_pos": 16512,
    "radiant": {
        "amount": 4,
        "destroyed": 0,
        "advantage": -1556,
        "duration": 360,
        "time_placed": 1684
    },
    "dire": {
        "amount": 9,
        "destroyed": 3,
        "advantage": 562,
        "duration": 300,
        "time_placed": 1151
    },
    "all": {
        "amount": 13,
        "destroyed": 3,
        "advantage": null,
        "duration": 330,
        "time_placed": 1418
    }
}
{
    "cluster_id": 24,
    "x_pos": 10294,
    "y_pos": 16994,
    "z_pos": 16512,
    "radiant": {
        "amount": 5,
        "destroyed": 2,
        "advantage": -1068,
        "duration": 227,
        "time_placed": 2350
    },
    "dire": {
        "amount": 28,
        "destroyed": 12,
        "advantage": 2685,
        "duration": 261,
        "time_placed": 1124
    },
    "all": {
        "amount": 33,
        "destroyed": 14,
        "advantage": null,
        "duration": 244,
        "time_placed": 1737
    }
}
{
    "cluster_id": 25,
    "x_pos": 20990,
    "y_pos": 17144,
    "z_pos": 16912,
    "radiant": {
        "amount": 60,
        "destroyed": 42,
        "advantage": 3467,
        "duration": 222,
        "time_placed": 1849
    },
    "dire": {
        "amount": 49,
        "destroyed": 31,
        "advantage": -4044,
        "duration": 201,
        "time_placed": 1964
    },
    "all": {
        "amount": 109,
        "destroyed": 73,
        "advantage": null,
        "duration": 212,
        "time_placed": 1906
    }
}
{
    "cluster_id": 26,
    "x_pos": 8666,
    "y_pos": 16056,
    "z_pos": 16640,
    "radiant": {
        "amount": 7,
        "destroyed": 4,
        "advantage": -799,
        "duration": 301,
        "time_placed": 1796
    },
    "dire": {
        "amount": 13,
        "destroyed": 6,
        "advantage": -179,
        "duration": 245,
        "time_placed": 1490
    },
    "all": {
        "amount": 20,
        "destroyed": 10,
        "advantage": null,
        "duration": 273,
        "time_placed": 1643
    }
}
{
    "cluster_id": 27,
    "x_pos": 8909,
    "y_pos": 17002,
    "z_pos": 16640,
    "radiant": {
        "amount": 3,
        "destroyed": 0,
        "advantage": 1607,
        "duration": 360,
        "time_placed": 1525
    },
    "dire": {
        "amount": 10,
        "destroyed": 7,
        "advantage": 2038,
        "duration": 198,
        "time_placed": 1456
    },
    "all": {
        "amount": 13,
        "destroyed": 7,
        "advantage": null,
        "duration": 279,
        "time_placed": 1490
    }
}
{
    "cluster_id": 28,
    "x_pos": 19416,
    "y_pos": 23029,
    "z_pos": 16640,
    "radiant": {
        "amount": 7,
        "destroyed": 6,
        "advantage": 5737,
        "duration": 173,
        "time_placed": 2127
    },
    "dire": {
        "amount": 2,
        "destroyed": 0,
        "advantage": -5122,
        "duration": 360,
        "time_placed": 1916
    },
    "all": {
        "amount": 9,
        "destroyed": 6,
        "advantage": null,
        "duration": 266,
        "time_placed": 2022
    }
}
{
    "cluster_id": 29,
    "x_pos": 9338,
    "y_pos": 13268,
    "z_pos": 16640,
    "radiant": {
        "amount": 7,
        "destroyed": 4,
        "advantage": -10600,
        "duration": 180,
        "time_placed": 3069
    },
    "dire": {
        "amount": 1,
        "destroyed": 0,
        "advantage": 4372,
        "duration": 360,
        "time_placed": 2138
    },
    "all": {
        "amount": 8,
        "destroyed": 4,
        "advantage": null,
        "duration": 270,
        "time_placed": 2604
    }
}
{
    "cluster_id": 30,
    "x_pos": 15106,
    "y_pos": 18938,
    "z_pos": 16640,
    "radiant": {
        "amount": 7,
        "destroyed": 2,
        "advantage": -1651,
        "duration": 271,
        "time_placed": 1057
    },
    "dire": {
        "amount": 6,
        "destroyed": 1,
        "advantage": 861,
        "duration": 345,
        "time_placed": 1018
    },
    "all": {
        "amount": 13,
        "destroyed": 3,
        "advantage": null,
        "duration": 308,
        "time_placed": 1038
    }
}
{
    "cluster_id": 31,
    "x_pos": 15610,
    "y_pos": 19970,
    "z_pos": 16912,
    "radiant": {
        "amount": 78,
        "destroyed": 33,
        "advantage": 337,
        "duration": 278,
        "time_placed": 928
    },
    "dire": {
        "amount": 56,
        "destroyed": 25,
        "advantage": -217,
        "duration": 268,
        "time_placed": 1315
    },
    "all": {
        "amount": 134,
        "destroyed": 58,
        "advantage": null,
        "duration": 273,
        "time_placed": 1122
    }
}
{
    "cluster_id": 32,
    "x_pos": 24572,
    "y_pos": 10505,
    "z_pos": 16502,
    "radiant": {
        "amount": 3,
        "destroyed": 0,
        "advantage": 3487,
        "duration": 360,
        "time_placed": 2053
    },
    "dire": {
        "amount": 3,
        "destroyed": 1,
        "advantage": -6480,
        "duration": 260,
        "time_placed": 2685
    },
    "all": {
        "amount": 6,
        "destroyed": 1,
        "advantage": null,
        "duration": 310,
        "time_placed": 2369
    }
}
{
    "cluster_id": 33,
    "x_pos": 10919,
    "y_pos": 13036,
    "z_pos": 16640,
    "radiant": {
        "amount": 4,
        "destroyed": 4,
        "advantage": -5782,
        "duration": 105,
        "time_placed": 2752
    },
    "dire": {
        "amount": 11,
        "destroyed": 10,
        "advantage": 969,
        "duration": 118,
        "time_placed": 2680
    },
    "all": {
        "amount": 15,
        "destroyed": 14,
        "advantage": null,
        "duration": 112,
        "time_placed": 2716
    }
}
{
    "cluster_id": 34,
    "x_pos": 23080,
    "y_pos": 18904,
    "z_pos": 16640,
    "radiant": {
        "amount": 6,
        "destroyed": 4,
        "advantage": 2810,
        "duration": 169,
        "time_placed": 2230
    },
    "dire": {
        "amount": 12,
        "destroyed": 7,
        "advantage": -4552,
        "duration": 197,
        "time_placed": 2272
    },
    "all": {
        "amount": 18,
        "destroyed": 11,
        "advantage": null,
        "duration": 183,
        "time_placed": 2251
    }
}
{
    "cluster_id": 35,
    "x_pos": 20236,
    "y_pos": 11780,
    "z_pos": 16920,
    "radiant": {
        "amount": 97,
        "destroyed": 43,
        "advantage": -602,
        "duration": 274,
        "time_placed": 1101
    },
    "dire": {
        "amount": 114,
        "destroyed": 61,
        "advantage": -273,
        "duration": 226,
        "time_placed": 1081
    },
    "all": {
        "amount": 211,
        "destroyed": 104,
        "advantage": null,
        "duration": 250,
        "time_placed": 1091
    }
}
{
    "cluster_id": 36,
    "x_pos": 12070,
    "y_pos": 12413,
    "z_pos": 16640,
    "radiant": {
        "amount": 2,
        "destroyed": 2,
        "advantage": -8856,
        "duration": 54,
        "time_placed": 2016
    },
    "dire": {
        "amount": 3,
        "destroyed": 3,
        "advantage": 13305,
        "duration": 66,
        "time_placed": 2549
    },
    "all": {
        "amount": 5,
        "destroyed": 5,
        "advantage": null,
        "duration": 60,
        "time_placed": 2282
    }
}
{
    "cluster_id": 37,
    "x_pos": 21462,
    "y_pos": 19196,
    "z_pos": 16640,
    "radiant": {
        "amount": 10,
        "destroyed": 10,
        "advantage": 903,
        "duration": 49,
        "time_placed": 2446
    },
    "dire": {
        "amount": 3,
        "destroyed": 3,
        "advantage": 1785,
        "duration": 145,
        "time_placed": 2103
    },
    "all": {
        "amount": 13,
        "destroyed": 13,
        "advantage": null,
        "duration": 97,
        "time_placed": 2274
    }
}
{
    "cluster_id": 38,
    "x_pos": 11964,
    "y_pos": 13678,
    "z_pos": 16512,
    "radiant": null,
    "dire": {
        "amount": 5,
        "destroyed": 4,
        "advantage": 2400,

In [12]:
average_df = grouped.reset_index('is_radiant')
average_radiant = average_df[average_df['is_radiant'] == True]
average_dire = average_df[average_df['is_radiant'] == False]
average = {
    'cluster_id': -1,
    'radiant': {
        'advantage': round(average_radiant['advantage'].mean()),
        'duration': round(average_radiant['duration'].mean()),
    },
    'dire': {
        'advantage': round(average_dire['advantage'].mean()),
        'duration': round(average_dire['duration'].mean()),
    },
    'all': {
        'advantage': None,
        'duration': round(average_df['duration'].mean()),
    }
}
average

{'cluster_id': -1,
 'radiant': {'advantage': -954, 'duration': 284},
 'dire': {'advantage': 322, 'duration': 273},
 'all': {'advantage': None, 'duration': 279}}